### ISSUE TITLE
DAO Governing Body

### ISSUE THREAD

**Issue by cl-tim** [congruentlabs/signata-dao#1]
_The modification to be made (e.g. add new DAO proposer):_

Selecting the first DAO proposers.

_The purpose of the modification, and a justification as to requiring the modification to be made:_

Congruent Labs as DAO Custodian will not act as proposal managers for the project. A starting cohort of 5 volunteers to join the role of proposal manager is needed to establish the DAO management. Duties for this role include:

1. Actively managing these GitHub issues (removing spam, invalid requests, etc.)
2. From diverse time zones. We don't want every proposal manager living within a single time zone.
3. Willing to pay gas to create proposals using the DAO Governance dashboard.

Individuals requesting consideration for being accepted into this role must provide their GitHub username, their wallet address, their time zone, and an explanation as to why they are suitable as a Proposal Manager into the comments of this post.

Future proposals may request to remove anyone in the role of Proposal Manager if they believe they are underperforming in their duties.

**Comment by RunningWithTurtles** [comment]
GitHub Username: SATAcolyte
Wallet address: 0xe171e4d20c7d50d20e8eed6c1c6d8287fb223ba4 -    eth/sata
0xf432c4cb3a9914afe61a08066008d5d22ba8fe5b - bsc/sata eth/dsata
Time zone: GMT +4

I have only been in crypto for a short time (two years) but I have a good understanding of Sata, Blockchain technology and DAOs.  I see great potential for the project and since I am semi-retired I have plenty of time on my hands.

**Comment by SataCenturion** [comment]
GitHub Username: SataCenturion
Wallet address: 0x5e8073db3c55dfe04c8a40b0de140fd36f82f76a - eth/sata
Time zone: GMT +8

Have been with Sata since the launch in April 2021, Active member and community admin of the SATA telegram group. I see SATA as key to a future in Web3 free of Centralized identity control, tracking and commodification of user identity. 

I am not an expert Github user but am happy to pay gas to create proposals and assist as required or to act as a steward until replaced by another Proposal Manager.

**Comment by kingmick** [comment]
Github username: Kingmick
Wallet address: 0x0DC4a068432430438872bAbb1Fd678ca92291960 - eth/sata
Time zone: GMT -5

Have been in SATA for over a year. Big believe in the project and team.

I'm not a crypto expert, but I'm happy to listen and help out if needed.

**Comment by Satamarok** [comment]
Github username: Satamarok
Wallet address: 0x3853599fEb7f8777407d17cBaf739E67440cd88a
Eth/SATA/dSata
Time zone: GMT+1

Been in SATA since day one, and a huge believer in what they're trying to achieve.
Not a Github expert, but more than happy to learn and help the project to progress

**Comment by cl-tim** [comment]
Don't worry, it's very easy, and you'll see how it works as we get the first one through to vote.

The most important thing is that the DAO control is delegated to the community.

**Comment by Satamarok** [comment]
Thanks, Tim
Looking forward to playing my part, and hope others soon follow suit :)

**Comment by SATA-OG** [comment]
Github Username: SATA-OG
Wallet Address - 0x60338c1e934B3fdD37f33054423333B7970434Ff
Timezone: UTC+1

Been involved with Signata since the beginning and hold a nice amount of both SATA and dSATA at this point

Very interested in what the future holds for Signata and SATA / dSATA

Will be glad to look after the role of Proposal Manager if elected.

**Comment by BIGDOGGYSTYLER** [comment]
Github Username: SATAsenor
Wallet Address - 0x210F8F807e779058b7Fa42771F4De66B6a0e6D83
Timezone: GMT +12

Have been in Signata since the airdrop. Holding both dSATA and SATA.

I've always thought of the project as being both innovative and essential for the future of web3.

Happy to be a Proposal Manager.

**Comment by cl-tim** [comment]
Opening proposal on chain for the 6 proposers:

GitHub Username: SATAcolyte
Wallet address: 0xe171e4d20c7d50d20e8eed6c1c6d8287fb223ba4 - eth/sata
0xf432c4cb3a9914afe61a08066008d5d22ba8fe5b - bsc/sata eth/dsata
Time zone: GMT +4

GitHub Username: SataCenturion
Wallet address: 0x5e8073db3c55dfe04c8a40b0de140fd36f82f76a - eth/sata
Time zone: GMT +8

Github username: Kingmick
Wallet address: 0x0DC4a068432430438872bAbb1Fd678ca92291960 - eth/sata
Time zone: GMT -5

Github username: Satamarok
Wallet address: 0x3853599fEb7f8777407d17cBaf739E67440cd88a
Eth/SATA/dSata
Time zone: GMT+1

Github Username: SATA-OG
Wallet Address - 0x60338c1e934B3fdD37f33054423333B7970434Ff
Timezone: UTC+1

Github Username: SATAsenor
Wallet Address - 0x210F8F807e779058b7Fa42771F4De66B6a0e6D83
Timezone: GMT +12

Opened proposal: https://www.tally.xyz/proposal/b1de4c62-d43c-4a0c-9d32-e022721ac87e

**Comment by cl-tim** [comment]
Vote: Succeeded
Block number: 14870264

**Comment by cl-tim** [comment]
All 6 proposers have been invited as maintainers of this GitHub repository to manage issues.

**Comment by cl-tim** [comment]
Granting PROPOSER (0xb09aa5aeb3702cfd50b6b62bc4532604938f21248a27a1d5ca736082b6819cc1) on Timelock contract:

0x30b0106d9140902d7d495a7f21d282852e9f59d8

For:

0xe171e4d20c7d50d20e8eed6c1c6d8287fb223ba4
0x5e8073db3c55dfe04c8a40b0de140fd36f82f76a
0x0DC4a068432430438872bAbb1Fd678ca92291960
0x3853599fEb7f8777407d17cBaf739E67440cd88a
0x60338c1e934B3fdD37f33054423333B7970434Ff
0x210F8F807e779058b7Fa42771F4De66B6a0e6D83

Transactions:

https://etherscan.io/tx/0x694b3ef52e962059c49157e7bcf9f9ce8dc6dd5e8a87678c7c023375d3077e8f
https://etherscan.io/tx/0x043bc45385ade7460be97d2524d14a3cf15c350cb4c8e0c498c7ac3c031fe7d7
https://etherscan.io/tx/0xb98feb33deebc9a9d9bee663e71fcdfd94ed698893195b8b2a9b78cd2daba490
https://etherscan.io/tx/0xc69e8d6b9dba056be02466ab83b6a9d7f2a2c6f6f06130354a846106bcbdd810
https://etherscan.io/tx/0xc7500281c77d96e73b4ab3ed88c676a525ee9b2a6693d99c6e53d202138fb2bd
https://etherscan.io/tx/0x2b9c9708a85a933eb909f927a09d978110578ca73776b70d12d71a898ee41ea0
